user_profile_query = "SELECT p.daily_quota, p.night_start, p.night_end, p.speed_down, p.speed_up \
                      FROM raduserprofile up \
                      JOIN radprofile p ON up.profile_id = p.id \
                      WHERE up.username = '%{SQL-User-Name}'"