sqlcounter dailyquota {
    sql_module_instance = sql
    counter_name = Daily-Quota
    check_name = Max-Daily-Quota
    reply_name = Daily-Quota-Limit
    key = User-Name
    query = "SELECT SUM(usage) FROM radusagestats WHERE username = '%{${key}}' AND day = CURDATE()"
    reset = never
}