sqlcounter dailyquota {
    sql_module_instance = sql
    counter_name = Daily-Quota
    check_name = Max-Daily-Quota
    reply_name = Daily-Quota-Limit
    key = User-Name
    query = "SELECT COALESCE(SUM(data_usage), 0) FROM radusagestats WHERE username = '%{${key}}' AND day = CURDATE()"
    reset = daily
    reset_time = "00:00"
}