# client my-nas {
#     ipaddr = 172.18.0.1
#     secret = tisp123
#     nas_type = other
#     require_message_authenticator = no
# }

# client localhost {
#     ipaddr = 127.0.0.1
#     secret = testing123
#     nas_type = other
#     require_message_authenticator = no
# }