home_server coa_server {
    type = coa
    ipaddr = 172.18.0.1   # NAS IP (your router/switch)
    port = 1700
    secret = tisp123     # MUST match NAS configuration
    require_message_authenticator = no
    response_window = 20
}

home_server_pool coa_pool {
    type = fail_over
    home_server = coa_server
}
